---
title: "C testing"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---


```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(isoprocessorCUB)
library(readxl)
library(knitr)
library(tidyverse)
library(plotly)
```


# Load data

```{r}
data <- readRDS(file.path("tmp", "c_standards_test.rds"))
```


## Retrieve metadata

```{r}
metadata_samples <- read_excel(file.path("tmp", "C_metadata.xlsx"), sheet = "files")
metadata_peak_maps <- read_excel(file.path("tmp","C_metadata.xlsx"), sheet = "maps")
kable(metadata_samples)
```

## Map peaks

```{r, results='asis'}
data_w_peaks <- 
  data %>% 
  iso_set_default_process_parameters(
    map_id = map_id,
    rt = Rt,
    rt_start = Start,
    rt_end = End,
    file_id = file_id,
    print_func = kable
    ) %>% 
  iso_show_default_processor_parameters() %>% 
  # add in metadata
  iso_add_metadata(metadata_samples, match_by = c(`Identifier 1`, Analysis)) %>%
  iso_print_data_table (select = c(file_id, Analysis, `Identifier 1`), filter = !has_metadata, 
                        title = "Info: records with missing metadata:") %>% 
  # only continue with records that have metadata and those that are flagged for processing
  filter(has_metadata, process == "yes") %>% 
  # map peaks
  iso_map_peaks(metadata_peak_maps) %>% 
  iso_print_data_table(select = c(file_id, compound, Start, Rt, End), filter = !is_identified | is_missing,
                       title = "Info: missing and unidentified peaks") %>% 
  # filter out the problematic peaks
  filter(is_identified, !is_missing, !is_ambiguous)
```

## Reference peaks

```{r "ref_variation", fig.width=8, fig.height=6}
data_w_peaks %>% 
  iso_set_default_process_parameters(
    group_id = Analysis,
    ratio = `R 13C/12C`
  ) %>% 
  iso_visualize_ref_peaks(is_ref_condition = is_ref_peak == "yes") 

data_w_peaks %>% 
  iso_visualize_ref_peaks(is_ref_condition = is_ref_peak == "yes", within_group = TRUE) 
```


# Data processing

## Focus on analytes 

Focus on the analytes and calculate a few summary parameters we want to use later.

```{r}
data_w_analyte_peaks <- 
  data_w_peaks %>% 
  # this is important so that the reference peaks are not caught up in the next set of calculations
  filter(is_ref_peak == "no") %>% 
  # for each analysis calculate averages across analysis
  group_by(Analysis) %>% 
  mutate(
    ampl_sample_mean.mV = mean(`Ampl 44`), ampl_sample_sd.mV = sd(`Ampl 44`),
    area_sample_mean.Vs = mean(`Intensity 44`), area_sample_sd.Vs = sd(`Intensity 44`)
  )
```

## Standards

```{r}
standards <- read_excel(file.path("tmp", "GC-IRMS standards.xlsx"))
kable(standards)

data_w_stds <-
  data_w_analyte_peaks %>% 
  iso_add_standards(standards)  
```

## Calibration

```{r}
data_w_calibs <- data_w_stds %>% 
  # prepare for calibration by defining the grouping column(s) and setting default parameters
  iso_prepare_for_calibration(group_by = c(Analysis)) %>% 
  iso_set_default_process_parameters(delta_residual = resid_d13C) %>% 
  # run calibration
  iso_calibrate_delta(model = lm(`d 13C/12C` ~ true_d13C)) %>% 
  # pull out some columns we want generally available
  iso_unnest_calib_data(select = c(starts_with("Id"), ampl_sample_mean.mV)) 

data_w_calibs %>% 
  iso_unnest_delta_calib_summary(keep_other_list_data = FALSE) %>% 
  kable(digits =3)

data_w_calibs %>% 
  # pull out seed oxidation in addition
  iso_unnest_calib_data(select = `Seed Oxidation`) %>% 
  iso_unnest_delta_calib_coefs(select = c(-statistic), keep_other_list_data = FALSE) %>% 
  # arrange by term and Analysis to get a quick idea of what the numbers across analyses
  arrange(term, Analysis) %>% 
  kable(digits = 2)
```

## Standards

#### Parameters

```{r "calibration_parameters", fig.width = 8, fig.height = 8}
data_params <- data_w_calibs %>% 
  # pull out remaining columns we want available (some might already be pulled out but that's okay)
  iso_unnest_calib_data(select = c(file_datetime, ampl_sample_mean.mV, Preparation, is_standard)) 
  
# visualize the delta calibration fits
data_params %>% 
  iso_visualize_delta_calib_fits(x = Analysis, color = `Identifier 2`, shape = Preparation, size = ampl_sample_mean.mV,
                                 include_from_summary = c(adj.r.squared, deviance)) + labs(title = "parameters vs. analysis")

data_params %>% 
  iso_visualize_delta_calib_fits(x = ampl_sample_mean.mV, color = `Identifier 2`, shape = Preparation, size = ampl_sample_mean.mV,
                                 include_from_summary = c(adj.r.squared, deviance)) + labs(title = "parameters vs. amplitude") 

data_params %>% 
  iso_visualize_delta_calib_fits(x = file_datetime, color = `Identifier 2`, shape = Preparation, size = ampl_sample_mean.mV,
                                 include_from_summary = c(adj.r.squared, deviance)) + labs(title = "parameters vs. time")
```

```{r "interactive_calibration_parameters", fig.width = 8, fig.height = 8}
# turn the last plot into an interactive one
ggplotly(ggplot2::last_plot() + theme(legend.position = "none"))
```

#### Compounds

```{r "standards_by_compound", fig.width = 8, fig.height = 8}
data_w_calibs %>% 
  # pull out relevant data
  iso_unnest_calib_data(select = everything()) %>% 
  filter(is_standard) %>% 
  # calculate deviation from means
  group_by(Analysis) %>% 
  mutate(
    `Var: residual d13C [permil]` = resid_d13C,
    `Var: area diff from mean [%]` = (`Intensity 44`/mean(`Intensity 44`) - 1) * 100,
    `Var: amplitude diff from mean [%]` = (`Ampl 44`/mean(`Ampl 44`) - 1) * 100
  ) %>%
  # visualize
  iso_visualize_data(x = compound, y = starts_with("Var"), group = Analysis, color = `Identifier 2`)
```

```{r "interactive", fig.width = 8, fig.height = 8}
ggplotly()
```

