
#' Export calibration to Excel
#'
#' This function exports the passed in calibration(s) data frame to Excel. The different kinds of information (all data, model coefficients, summary, evaluation range) are exported to separate tabs within the excel file. If there are multiple different calibrations in the data frame (i.e. multiple \code{*calib_params} columns), ALL will be exported with different tabs for each.
#'
#' @param calibs_df calibration(s) data frame (i.e. the output of functions like \link{iso_generate_calibration}, \link{iso_apply_calibration}, \link{iso_evaluate_calibration_range}). Must still be nested (i.e. before running any of the \code{iso_unnest...} functions) to make sure it contains alll information.
#' @param filepath the path where to store the Excel file.
#' @param include_all_data whether to include a tab for all the peak data - if this function is called after \link{iso_apply_calibration} this will include
#' @param include_model_coefs whether to include a tab for the model coefficients
#' @param include_model_summary whether to include a tab for the model summary
#' @param include_model_range whether to include a tab for the evaluation range (if available, i.e. generated by \link{iso_evaluate_calibration_range})
#' @return returns the \code{calib} object invisibly for use in pipelines
#' @export
iso_export_calibration_to_excel <- function(
  calibs_df, filepath,
  include_all_data = TRUE, include_model_coefs = TRUE,
  include_model_summary = TRUE, include_model_range = TRUE,
  quiet = default(quiet)) {

  # safety checks
  if(missing(calibs_df) || !is.data.frame(calibs_df)) stop("calibs_df must be a data frame", call. = FALSE)
  if(!"all_data" %in% names(calibs_df)) stop("no all_data column, make sure this is still a nested calibration data frame (i.e. the direct output of iso_generate_calibration, iso_apply_calibration, or iso_evaluate_calibration_range", call. = FALSE)
  if(!is(calibs_df$all_data, "list")) stop("all_data column is not a list, make sure this is still a nested calibration data frame (i.e. the direct output of iso_generate_calibration, iso_apply_calibration, or iso_evaluate_calibration_range", call. = FALSE)
  calibs <- find_calibrations(calibs_df)
  if (length(calibs) == 0) stop("there do not seem to be any calibrations in this data frame, make sure to generate calibrations using iso_generate_calibration", call. = FALSE)

  # path
  filepath <- isoreader:::get_export_filepath(filepath, "xlsx")

  # info
  if (!quiet) {
    glue::glue("Info: exporting calibrations into Excel '{basename(filepath)}'... ") %>%
      message(appendLF = FALSE)
  }

  # make excel workbook
  wb <- openxlsx::createWorkbook()
  hs <- openxlsx::createStyle(textDecoration = "bold")

  ws_names <- c()

  # all data
  if (include_all_data) {
    ws_names <- c(ws_names, "all data")
    openxlsx::addWorksheet(wb, tail(ws_names, 1))
    all_data <- calibs_df %>% iso_unnest_data(keep_other_list_data = FALSE)
    openxlsx::writeData(wb, tail(ws_names, 1), all_data, headerStyle = hs)
  }

  # all calibs
  for(calib in calibs) {

    calib_vars <- get_calibration_vars(calib)

    # model coefs
    if (include_model_coefs) {
      ws_names <- c(ws_names, if (calib == "") "coefs" else paste(calib, "coefs"))
      openxlsx::addWorksheet(wb, tail(ws_names, 1))
      model_coefs <- calibs_df %>% iso_unnest_calibration_coefs(
        calibration = calib, keep_other_list_data = FALSE)
      openxlsx::writeData(wb, tail(ws_names, 1), model_coefs, headerStyle = hs)
    }

    # model summary
    if (include_model_summary) {
      ws_names <- c(ws_names, if (calib == "") "summary" else paste(calib, "summary"))
      openxlsx::addWorksheet(wb, tail(ws_names, 1))
      model_summary <- calibs_df %>% iso_unnest_calibration_summary(
        calibration = calib, keep_other_list_data = FALSE)
      openxlsx::writeData(wb, tail(ws_names, 1), model_summary, headerStyle = hs)
    }

    # model range
    if (include_model_range) {
      ws_names <- c(ws_names, if (calib == "") "range" else paste(calib, "range"))
      openxlsx::addWorksheet(wb, tail(ws_names, 1))
      tryCatch({
        model_range <- calibs_df %>% iso_unnest_calibration_range(
          calibration = calib, keep_other_list_data = FALSE)
        openxlsx::writeData(wb, tail(ws_names, 1), model_range, headerStyle = hs)
      }, error = function(e) {
        if (stringr::str_detect(e$message, fixed("'model_range' not found"))) {
          glue::glue(
            "calibration {if(calib == '') '' else paste0(calib, ' ')} does not ",
            "have a model range defined, tab will be empty. ",
            "Make sure to run iso_evaluate_calibration_range ",
            "first if these should be exported.") %>%
            warning(immediate. = TRUE, call. = FALSE)
        } else
          stop(e$message, call. = FALSE)
      })
    }
  }

  openxlsx::saveWorkbook(wb, filepath, overwrite = TRUE)

  # info
  if (!quiet) {
    glue::glue("complete. Created tabs '{glue::glue_collapse(ws_names, sep = \"', '\", last = \"' and '\")}'.") %>%
      message()
  }

  return(invisible(calibs_df))
}
