
#' Export calibration to Excel
#'
#' This function exports the passed in calibration(s) data frame to Excel. The different kinds of information (all data, model coefficients, summary, evaluation range) are exported to separate tabs within the excel file. If there are multiple different calibrations in the data frame (i.e. multiple \code{*calib_params} columns), ALL will be exported with different tabs for each.
#'
#' @param calibs_df data frame that includes calibration columns (i.e. the output of functions like \link{iso_generate_calibration}, \link{iso_apply_calibration}, \link{iso_evaluate_calibration_range}). Can be the output from \link{iso_get_calibration_data} if called after a calibration has been generated.
#' @param filepath the path where to store the Excel file.
#' @param ... named list of additional data frames to include in the summary (each will get their own tab)
#' @param include_all_data whether to include a tab for all the peak data - if this function is called after \link{iso_apply_calibration} this will include
#' @param include_calib_coefs whether to include a tab for the model coefficients
#' @param include_calib_summary whether to include a tab for the model summary
#' @param include_calib_range whether to include a tab for the evaluation range (if available, i.e. generated by \link{iso_evaluate_calibration_range})
#' @param with_explicit_units whether to include units in all column names
#' @return returns the \code{calib} object invisibly for use in pipelines
#' @export
iso_export_calibration_to_excel <- function(
  calibs_df, filepath, ...,
  include_all_data = TRUE, include_calib_coefs = TRUE,
  include_calib_summary = TRUE, include_calib_range = TRUE,
  with_explicit_units = TRUE,
  quiet = default(quiet)) {

  # safety checks
  if(missing(calibs_df) || !is.data.frame(calibs_df)) stop("calibs_df must be a data frame", call. = FALSE)
  if(!"all_data" %in% names(calibs_df)) {
    # requires nesting
    calibs_df <- iso_prepare_for_calibration(calibs_df, quiet = TRUE)
  }
  if(!is.list(calibs_df$all_data)) stop("all_data column is not a list, make sure this is still a nested calibration data frame (i.e. the direct output of iso_generate_calibration, iso_apply_calibration, or iso_evaluate_calibration_range", call. = FALSE)
  calibs <- all_calibrations(calibs_df)
  if (length(calibs) == 0) stop("there do not seem to be any calibrations in this data frame, make sure to generate calibrations using iso_generate_calibration", call. = FALSE)

  # explicit units
  with_units <- function(x) {
    if (with_explicit_units) iso_make_units_explicit(x)
    else x
  }

  # additional data
  add_data <- list(...)
  if (is.null(names(add_data)) || any(names(add_data) == ""))
    stop("additional data (...) must be named data frames", call. = FALSE)

  # path
  filepath <- isoreader:::get_export_filepath(filepath, "xlsx")

  # info
  if (!quiet) {
    glue::glue("Info: exporting calibrations into Excel '{basename(filepath)}'... ") %>%
      message()
  }

  # make excel workbook
  wb <- openxlsx::createWorkbook()
  hs <- openxlsx::createStyle(textDecoration = "bold")

  ws_names <- c()

  # additional data
  if (length(add_data) > 0) {
    for (tab in names(add_data)) {
      ws_names <- c(ws_names, tab)
      openxlsx::addWorksheet(wb, tail(ws_names, 1))
      openxlsx::writeData(wb, tail(ws_names, 1), with_units(add_data[[tab]]), headerStyle = hs)
    }
  }

  # all data
  if (include_all_data) {
    ws_names <- c(ws_names, "all data")
    openxlsx::addWorksheet(wb, tail(ws_names, 1))
    all_data <- calibs_df %>% iso_get_calibration_data(keep_calibration_parameters = FALSE, quiet = quiet)
    openxlsx::writeData(wb, tail(ws_names, 1), with_units(all_data), headerStyle = hs)
  }

  # all calibs
  for(calib in calibs) {

    calib_vars <- get_calibration_vars(calib)

    # model coefs
    if (include_calib_coefs) {
      ws_names <- c(ws_names, if (calib == "") "calib coefs" else paste(calib, "coefs"))
      openxlsx::addWorksheet(wb, tail(ws_names, 1))
      calib_coefs <- calibs_df %>% iso_get_calibration_coefficients(calibration = calib, quiet = quiet)
      openxlsx::writeData(wb, tail(ws_names, 1), calib_coefs, headerStyle = hs)
    }

    # model summary
    if (include_calib_summary) {
      ws_names <- c(ws_names, if (calib == "") "calib summary" else paste(calib, "summary"))
      openxlsx::addWorksheet(wb, tail(ws_names, 1))
      calib_summary <- calibs_df %>% iso_get_calibration_summary(calibration = calib)
      openxlsx::writeData(wb, tail(ws_names, 1), calib_summary, headerStyle = hs)
    }

    # model range
    if (include_calib_range && has_model_range(calibs_df, calibration = calib)) {
      ws_names <- c(ws_names, if (calib == "") "calib range" else paste(calib, "range"))
      openxlsx::addWorksheet(wb, tail(ws_names, 1))
      calib_range <- calibs_df %>% iso_get_calibration_range(calibration = calib, quiet = quiet)
      openxlsx::writeData(wb, tail(ws_names, 1), calib_range, headerStyle = hs)
    }
  }

  openxlsx::saveWorkbook(wb, filepath, overwrite = TRUE)

  # info
  if (!quiet) {
    glue::glue("Info: export complete, created tabs '{glue::glue_collapse(ws_names, sep = \"', '\", last = \"' and '\")}'.") %>%
      message()
  }

  return(invisible(calibs_df))
}
